ontology:
  directory: ../../owl/
  to-collapse:
    - ontology: SOMA-All
      out-path: ../../build/owl/current/SOMA.owl
      except: DUL
      new-iri: https://ease-crc.github.io/soma/owl/current/SOMA.owl
    - ontology: SOMA-HOME
      out-path: ../../build/owl/current/SOMA-HOME.owl
      except: DUL