ontology:
  directory: ../../owl/
  to-collapse:
    - ontology: SOMA-All
      out-path: ../../build/owl/current/SOMA.owl
    - ontology: SOMA-HOME
      out-path: ../../build/owl/current/SOMA-HOME.owl
